export let select_sector = [
  "Accounting ",
  "Advertising",
  "Architecture",
  "Automotive",
  "Aviation and Aerospace",
  "Call Center",
  "Education",
  "Energy and Utilities",
  "Engineering",
  "Executive/Management",
  "Financial Services",
  "Food Services",
  "Health Care",
  "Hospitality",
  "Human Resources",
  "Insurance",
  "Legal",
  "Mfg/Distribution and Trans.",
  "Military",
  "Other",
  "Personal Care and Services",
  "Property Maint and Facilities",
  "Public Works",
  "Publishing/Printing",
  "Real Estate",
  "Retail and Wholesale",
  "Sales and Marketing",
  "Science and Biotechnology",
  "Technology",
  "Telecommunication",
  "Transportation",
];
